#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

PS1='[\u@\h \W]\$ '


# XDG_CONFIG_HOME="$HOME/.config"

# Source global config
if [ -f $XDG_CONFIG_HOME/env ]; then
    source $XDG_CONFIG_HOME/env
fi
