# vi:syntax=sh
#!/usr/bin/env bash
#
# User configuration sourced by interactive shells
#

# check if running in a term emulator
IS_VIRTUAL_TERM=$(xhost >& /dev/null && echo "1")

# Source zim
if [[ -s ${ZDOTDIR:-${HOME}}/.zim/init.zsh ]]; then
  source ${ZDOTDIR:-${HOME}}/.zim/init.zsh
fi

if [[ $DISPLAY ]]; then 
  if command -v tmux>/dev/null; then
#    [[ ! $TERM =~ screen ]] && [ -z $TMUX ] && exec tmux
  fi
fi

XDG_CONFIG_HOME="$HOME/.config"

# Source global config
if [ -f $XDG_CONFIG_HOME/env-all ]; then
    source $XDG_CONFIG_HOME/env-all
fi

# Source nvm
if [ -f /usr/share/nvm/init-nvm.sh ]; then
    source /usr/share/nvm/init-nvm.sh
fi

# Source xiki if present
if [ -f $HOME/.xsh ]; then
    source $HOME/.xsh
fi

if hash fish 2>/dev/null; then
   exec fish
fi

# tabtab source for electron-forge package
# uninstall by removing these lines or running `tabtab uninstall electron-forge`
[[ -f /home/xananax/pushpin/node_modules/tabtab/.completions/electron-forge.zsh ]] && . /home/xananax/pushpin/node_modules/tabtab/.completions/electron-forge.zsh

# automatically start a tmux connection on login
if [[ -z "$TMUX" ]] && [ "$SSH_CONNECTION" != "" ]; then
    tmux attach-session -t ssh_tmux || tmux new-session -s ssh_tmux
fi
