

#
# User configuration sourced by interactive shells
#

# Source zim
if [[ -s ${ZDOTDIR:-${HOME}}/.zim/init.zsh ]]; then
  source ${ZDOTDIR:-${HOME}}/.zim/init.zsh
fi

if command -v tmux>/dev/null; then
#  [[ ! $TERM =~ screen ]] && [ -z $TMUX ] && exec tmux
fi


XDG_CONFIG_HOME="$HOME/.config"

# Source aliases
if [ -f $XDG_CONFIG_HOME/env-aliases ]; then
    source $XDG_CONFIG_HOME/env-aliases
fi

# Source paths
if [ -f $XDG_CONFIG_HOME/env-paths ]; then
    source $XDG_CONFIG_HOME/env-paths
fi

# Source exports
if [ -f $XDG_CONFIG_HOME/env-exports ]; then
    source $XDG_CONFIG_HOME/env-exports
fi


# Source functions
if [ -f $XDG_CONFIG_HOME/env-functions ]; then
    source $XDG_CONFIG_HOME/env-functions
fi

# Source nvm
if [ -f /usr/share/nvm/init-nvm.sh ]; then
    source /usr/share/nvm/init-nvm.sh
fi

# Source xiki if present
if [ -f $HOME/.xsh ]; then
    source $HOME/.xsh
fi

if hash fish 2>/dev/null; then
    fish
fi

