# vi:syntax=sh
#!/usr/bin/env bash
#
# User configuration sourced by interactive shells
#

# check if running in a term emulator
IS_VIRTUAL_TERM=$(xhost >& /dev/null && echo "1")

# Source zim
if [[ -s ${ZDOTDIR:-${HOME}}/.zim/init.zsh ]]; then
  source ${ZDOTDIR:-${HOME}}/.zim/init.zsh
fi

if [[ $DISPLAY ]]; then 
  if command -v tmux>/dev/null; then
#    [[ ! $TERM =~ screen ]] && [ -z $TMUX ] && exec tmux
  fi
fi

XDG_CONFIG_HOME="$HOME/.config"

# Source global config
if [ -f $XDG_CONFIG_HOME/env ]; then
    source $XDG_CONFIG_HOME/env
fi

# Source nvm
if [ -f /usr/share/nvm/init-nvm.sh ]; then
    source /usr/share/nvm/init-nvm.sh
fi

# Source xiki if present
if [ -f $HOME/.xsh ]; then
    source $HOME/.xsh
fi

if hash fish 2>/dev/null; then
   exec fish
fi

